### ISSUE TITLE
Dark mode flicker in Production

### ISSUE THREAD

**Issue by marcphilippebeaujean-abertay** [akzhy/gatsby-starter-elemental#19] opened 2020-04-18 10:29 UTC
First off, thanks for this great theme! I think I will contribute in due time.
My only problem is that the light mode flickers when I first load the page in production, but dark mode is enabled by default. Any ways around this or am I just doing something wrong?

**Comment by ahmad-reza619** [comment] 2020-04-18 15:27
Hello @marcphilippebeaujean-abertay thanks for reporting issue.

I think because the default background in most browser is white, and that is why it flickers. it takes time for react to apply the styles. what do you think @akzhy 

Edit:
Sorry after further research yes, it's normally wouldn't flicker on first load. we use less and webpack loaders for less, so it could be the styles were loaded asynchronously by webpack on prod.

[This](https://github.com/webpack-contrib/sass-loader/tree/e81fa62974556049fc5063c11089fb97581d9410#extracting-stylesheets) is some lead that i've found regarding this issue.

**Comment by marcphilippebeaujean-abertay** [comment] 2020-04-18 20:59
Thanks for getting back to me. Does this mean I'm the only one experiencing this issue? Or is this also in the repository?

**Comment by ahmad-reza619** [comment] 2020-04-19 04:20
I will try to reproduce the issue, but sadly I'm busy at the moment. I'll get back to you when I'm done.

**Comment by akzhy** [comment] 2020-04-20 08:44
Hey @marcphilippebeaujean-abertay , sorry for the delay in response. This is because of an issue in adding class to the body. I will try to create a workaround to fix it.

**Comment by marcphilippebeaujean-abertay** [comment] 2020-04-20 11:52
No worries. I also made some other fixes and added a cookie banner, can I push these to the repository?

**Comment by akzhy** [comment] 2020-05-25 17:04
Hey @marcphilippebeaujean-abertay sorry for the really long delay in responding. Pull requests are welcomed and appreciated, checkout #22 , the latest version. contributions to it are welcomed.

**Comment by baart1989** [comment] 2020-06-13 19:52
There is a way to fix it with custom html.js.

As explained in following blog [post](https://blog.maximeheckel.com/posts/switching-off-the-lights-part-2-fixing-dark-mode-flashing-on-servered-rendered-website)

**Comment by akzhy** [comment] 2020-06-23 07:18
Fixed in the latest version

**Closed as completed by akzhy** 2020-06-23 07:18 UTC
Labels: help wanted
