### ISSUE TITLE
Loading Issue with profile Images

### ISSUE THREAD

**Issue by Madgeniusblink** [akzhy/gatsby-starter-elemental#5] opened 2019-09-05 07:07 UTC
Hi I was wondering if anyone perhaps knows how to fix the loading issue happening here:https://elemental.netlify.com/
If you point me in the right direction I would be more than happy to fix it but I have no idea why its happening

**Comment by akzhy** [comment] 2019-09-05 08:25
Hi @Madgeniusblink can you give a bit more details on what the issue is ? Which part of the page is not loading ?

**Comment by akzhy** [comment] 2019-09-10 16:21
Hey @Madgeniusblink , I am closing this issue since you haven't responded. Also do check the demo again, I have made some new changes, which may have fixed your issue.

**Comment by Madgeniusblink** [comment] 2019-09-10 22:45
Hey @akzhy  sorry for the delay! It seems with your new update it has fixed the loading of the profile images, it was more noticeable on mobile! 
Thank you for updating the issue!

**Comment by akzhy** [comment] 2019-09-11 07:21
Great, glad I could help @Madgeniusblink

**Closed as completed by akzhy** 2019-09-11 07:21 UTC
